### ISSUE TITLE
Employee and Core Api Fixes

### ISSUE THREAD

**Issue by souravahmed1** [amitkverma/nestjs-microservice-boilerplate#7]
- [x] Employee Email Unique
- [x] Users Email Unique.
- [x] Seed Roles with SuperAdmin, Admin, HR
- [x] Proper Message when `tenant is inactive and its users is trying to log in`

**Comment by souravahmed1** [comment]
![image](https://user-images.githubusercontent.com/114906466/204452603-4931c751-ea33-4136-baee-73bb2add1b90.png)

- [x] Search Functionality was missing.

**Comment by souravahmed1** [comment]
- [x] Create Emploiyee, Unique KEY constrain failed
- [x] Tenant Name Unique Key

**Comment by souravahmed1** [comment]
```
throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
Error:
Invalid `prisma.employee.createMany()` invocation:


Foreign key constraint failed on the field: `Employee_companyTitleId_fkey (index)`
    at RequestHandler.handleRequestError (/Users/inno/Desktop/Projects/consultbae/nestjs-microservice-boilerplate/node_modules/@prisma/client/runtime/index.js:34310:13)
    at RequestHandler.request (/Users/inno/Desktop/Projects/consultbae/nestjs-microservice-boilerplate/node_modules/@prisma/client/runtime/index.js:34293:12)
    at PrismaService._request (/Users/inno/Desktop/Projects/consultbae/nestjs-microservice-boilerplate/node_modules/@prisma
```

- [x] Bulk Upload Err
